{% set name = "convertFQ" %}
{% set version = "0.1.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 51ded96ec2a9140c14e3fc5e52dc24643fccbe4bc781f44fffb3f2ace82102be

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: GNU GENERAL PUBLIC V3
  license_family: GPL3
  license_file: LICENSE.md
  summary: "convertFQ is used to convert either DNA2RNA or RNA2DNA in a fastq file"
  doc_url: https://github.com/NuruddinKhoiry/convertFQ/blob/master/README.md
  dev_url: 

extra:
  recipe-maintainers:
    - NuruddinKhoiry
